services:
  bookstore-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 5

  bookstore-app:
    image: "${APP_IMAGE}"
    restart: always
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}"
    env_file: .env
    depends_on:
      bookstore-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  bookstore-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:80
    environment:
      BACKEND_HOST: "bookstore-app"
      BACKEND_PORT: "5000"
    depends_on:
      bookstore-app:
        condition: service_healthy
    volumes:
       - ./nginx/bookstore.conf:/etc/nginx/nginx.conf.template  
       - ./app/static:/static
    command: >
      sh -c "envsubst '$$BACKEND_HOST $$BACKEND_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  pg_data:
